
jobs:

- job: 'Test'
  pool: 'Hosted macOS'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    displayName: Install Poetry

  - script: python -m venv $(System.DefaultWorkingDirectory)
    displayName: Create virtual environment

  - script: |
      source bin/activate
      $HOME/.poetry/bin/poetry install
    displayName: 'Install dependencies'

  - script: |
      source bin/activate
      python -m black -l 100 --check localizationkit/*.py
    displayName: 'Format Check (Black)'

  - script: |
      source bin/activate
      python -m pylint --rcfile=pylintrc localizationkit
      python -m pylint --rcfile=pylintrc tests
    displayName: 'Lint'

  - script: |
      source bin/activate
      python -m mypy --ignore-missing-imports localizationkit/
      python -m mypy --ignore-missing-imports tests/
    displayName: 'Type Check'

  - script: |
      source bin/activate
      python -m pytest tests --cov=localizationkit --cov-report xml --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  # Publish Code Coverage Results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
